Repository lienputnina/react-components-for-you, pull requests merged in 2022-10, with the labels that each got.

#1 Color palette
  .storybook/main.js
  example/yarn.lock
  package.json
  src/index.scss
  src/index.ts
  src/styles/scss/colors.scss
  src/styles/scss/global.scss
  src/styles/stories/Colors.stories.mdx
  yarn.lock
Labels: enhancement

#2 Feat: added custom paddings
  src/styles/scss/paddings.scss
  src/styles/stories/Colors/Colors.stories.mdx
  src/styles/stories/Paddings/PaddingExample.scss
  src/styles/stories/Paddings/PaddingExample.stories.tsx
  src/styles/stories/Paddings/PaddingExample.tsx
Labels: enhancement

#6 chore: added vscode workspace for project
  .gitignore
  .vscode/react-components-for-you.code-workspace
  package.json
  src/test/setupTests.tsx
Labels: chore

#4 refactor: exported color variables for color story
  src/components/Button/Button.stories.tsx
  src/styles/scss/colors.scss
  src/styles/scss/paddings.scss
  src/styles/stories/Colors/Colors.stories.mdx
  src/styles/stories/Colors/colors.module.scss
  src/styles/stories/Paddings/PaddingExample.stories.tsx
  src/styles/stories/Paddings/PaddingExample.tsx
Labels: refactor

#5 docs: updated readme with build steps
  .gitignore
  README.md
Labels: documentation

#3 Custom margins
  .storybook/preview.js
  example/yarn.lock
  package.json
  src/styles/scss/cssReset.scss
  src/styles/scss/global.scss
  src/styles/scss/margins.scss
  src/styles/stories/Margins/MarginExample.scss
  src/styles/stories/Margins/MarginExample.stories.tsx
  src/styles/stories/Margins/MarginExample.tsx
  src/styles/stories/Paddings/PaddingExample.scss
  src/styles/stories/Paddings/PaddingExample.tsx
Labels: enhancement

#7 feat: added typography examples
  package.json
  src/declaration.d.ts
  src/index.scss
  src/styles/scss/typography.scss
  src/styles/stories/Typography/TypographyExample.module.scss
  src/styles/stories/Typography/TypographyExample.stories.tsx
  src/styles/stories/Typography/TypographyExample.tsx
Labels: enhancement
