Repository lienputnina/react-components-for-you, pull requests merged in 2023-03, with the labels that each got.

#33 chore: updated the component structure: added interface extensions,..…
  package.json
  src/components/Button/Button.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/NumberInput/NumberInput.tsx
  src/components/RadioInputGroup/RadioInput/RadioInput.tsx
  src/components/RadioInputGroup/RadioInputGroup.tsx
  src/components/Switch/Switch.tsx
  src/components/Text/Text.tsx
  src/components/TextInput/TextInput.tsx
  src/components/Title/Title.tsx
Labels: chore

#36 feat: added elevations to library components
  package.json
  src/components/Button/Button.scss
  src/components/Dropdown/Dropdown.scss
  src/components/Header/Header.scss
  src/components/NumberInput/NumberInput.scss
  src/components/Switch/Switch.scss
  src/components/TextInput/TextInput.scss
  src/styles/scss/elevations.scss
  src/styles/stories/Elevations/ElevationsExample.scss
  src/styles/stories/Elevations/ElevationsExample.stories.tsx
  src/styles/stories/Elevations/ElevationsExample.tsx
  src/styles/stories/Margins/MarginsExample.scss
  src/styles/stories/Margins/MarginsExample.stories.tsx
  src/styles/stories/Margins/MarginsExample.tsx
  src/styles/stories/Paddings/PaddingsExample.scss
  src/styles/stories/Paddings/PaddingsExample.stories.tsx
  src/styles/stories/Paddings/PaddingsExample.tsx
Labels: chore, feat

#37 ci: disabled css modules
  package.json
  rollup.config.js
Labels: refactor
