Repository lienputnina/react-components-for-you, pull requests merged in 2023-02, with the labels that each got.

#29 docs: formatted readme code snippets
  README.md
Labels: documentation

#30 chore: set up husky git hooks
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: chore

#31 Feat/switch component
  package.json
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Switch/Switch.scss
  src/components/Switch/Switch.stories.tsx
  src/components/Switch/Switch.test.tsx
  src/components/Switch/Switch.tsx
  src/index.ts
  src/rcl.stories.tsx
Labels: feat

#32 chore: bumped library version
  package.json
Labels: chore
