Repository lienputnina/react-components-for-you, pull requests merged in 2023-01, with the labels that each got.

#17 feat: implemented RadioButtonGroup component
  .gitignore
  .vscode/react-components-for-you.code-workspace
  jest.config.ts
  src/components/RadioInputGroup/RadioInput/RadioInput.stories.tsx
  src/components/RadioInputGroup/RadioInput/RadioInput.test.tsx
  src/components/RadioInputGroup/RadioInput/RadioInput.tsx
  src/components/RadioInputGroup/RadioInputGroup.scss
  src/components/RadioInputGroup/RadioInputGroup.stories.tsx
  src/components/RadioInputGroup/RadioInputGroup.test.tsx
  src/components/RadioInputGroup/RadioInputGroup.tsx
Labels: feat

#18 feat: created the number input component
  .eslintrc.js
  package.json
  src/components/NumberInput/NumberInput.scss
  src/components/NumberInput/NumberInput.stories.tsx
  src/components/NumberInput/NumberInput.test.tsx
  src/components/NumberInput/NumberInput.tsx
  src/index.ts
  src/styles/scss/paddings.scss
Labels: feat

#21 chore: turned off no-props-spreading rule from eslint
  .eslintrc.js
  src/components/Header/Header.tsx
  src/components/NumberInput/NumberInput.tsx
  src/components/RadioInputGroup/RadioInput/RadioInput.tsx
  src/components/RadioInputGroup/RadioInputGroup.tsx
Labels: chore

#22 feat: added dropdown component
  .vscode/react-components-for-you.code-workspace
  README.md
  jest.config.ts
  package.json
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Header/Header.scss
  src/components/NumberInput/NumberInput.scss
  src/components/RadioInputGroup/RadioInput/RadioInput.stories.tsx
  src/components/RadioInputGroup/RadioInput/RadioInput.test.tsx
  src/components/RadioInputGroup/RadioInput/RadioInput.tsx
  src/components/RadioInputGroup/RadioInputGroup.stories.tsx
  src/components/RadioInputGroup/RadioInputGroup.test.tsx
  src/components/RadioInputGroup/RadioInputGroup.tsx
  src/constants/KeyCodes.ts
  src/index.ts
  src/styles/scss/colors.scss
  src/styles/scss/cssReset.scss
  src/styles/scss/mixins.scss
  src/styles/scss/variables.module.scss
  src/styles/stories/Colors/Colors.stories.mdx
  tsconfig.json
Labels: feat

#23 feat: added elevations
  src/styles/scss/elevation.scss
  src/styles/stories/Elevations/Elevation.stories.tsx
  src/styles/stories/Elevations/ElevationExample.scss
  src/styles/stories/Elevations/ElevationExample.tsx
  src/styles/stories/Margins/MarginExample.scss
  src/styles/stories/Margins/MarginExample.stories.tsx
  src/styles/stories/Paddings/PaddingExample.scss
  src/styles/stories/Paddings/PaddingExample.stories.tsx
Labels: feat

#24 chore: set up publish github action
  .github/workflows/npm-publish.yml
  package.json
Labels: chore

#25 chore: added build task in publish action
  .github/workflows/npm-publish.yml
Labels: chore

#27 docs: added a showcase story with all components
  src/components/Button/Button.scss
  src/components/Dropdown/Dropdown.scss
  src/components/NumberInput/NumberInput.scss
  src/components/RadioInputGroup/RadioInputGroup.scss
  src/components/TextInput/TextInput.scss
  src/rcl.stories.tsx
  src/styles/scss/mixins.scss
  tsconfig.json
Labels: documentation
